### PR TITLE
Upgrade aws-sdk to v2

### PR DESCRIPTION
**Pull request by eagletmt**
I'm testing this branch with my personal account.

Maybe many tests fail...

### CODE REVIEW

**Comment by winebarrel** [comment]
Would you like me to grant write access to the repository?

**Comment by eagletmt** [comment]
Now all tests are passing locally.

The Travis build is failing due to security restriction.
http://docs.travis-ci.com/user/pull-requests/#Security-Restrictions-when-testing-Pull-Requests
@winebarrel You can push my branch to winebarrel/roadworker to run tests in Travis.

**Comment by winebarrel** [comment]
> Now all tests are passing locally.

:+1: 

> @winebarrel You can push my branch to winebarrel/roadworker to run tests in Travis.

Thanks!

**Comment by eagletmt** [comment]
Yay!
:white_check_mark:  https://travis-ci.org/winebarrel/roadworker/builds/79006988

**Pull request merged**
